[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://task-management-app-1-nmv7.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {
    Access-Control-Allow-Origin = "https://fantastic-centaur-20d040.netlify.app",
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept",
    Access-Control-Allow-Credentials = "true"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://fantastic-centaur-20d040.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept"
    Access-Control-Allow-Credentials = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 